def manejo_de_errores(exception):
    print(f"Error{exception}")